#!/bin/bash
# Fetches real, public-domain EPUBs from Project Gutenberg for Sprint 10's
# round-trip proof against a real tool's own output – deliberately NOT
# generated by anything in this repository, which is the whole point:
# `ZipArchiveWriter` and `EPUBArchiveWriter` have only ever been proven
# against archives Shelf's own code wrote, and a real EPUB is always
# DEFLATE-compressed, which none of those fixtures are.
#
# They go to ~/Library/Caches/Shelf/real-epubs-10/, never into the
# repository: "no borrowed book goes into this repository" (CLAUDE.md) holds
# for a public-domain Gutenberg download exactly as it does for anything
# else. This script is what makes the set reproducible without keeping the
# books – run it again on a Mac that has never seen this cache and the same
# six files come back.
#
# Six books, deliberately different: EPUB 2 and EPUB 3, one with images and
# one without, one in German and one in French for non-ASCII text, plus one
# genuinely large book (Les Misérables) that neither this project's
# synthetic fixtures nor its "~60 MB stress test" has ever measured against
# something actually DEFLATE-compressed at that size.
#
# Usage: Scripts/real-epubs.sh [destination]
set -uo pipefail

DEST="${1:-$HOME/Library/Caches/Shelf/real-epubs-10}"
mkdir -p "$DEST"

fetch() {
    local url="$1" name="$2" reason="$3"
    local dest="$DEST/$name"
    if [ -s "$dest" ]; then
        echo "already have: $name ($reason)"
        return 0
    fi
    echo "fetching: $name ($reason)"
    if curl -sL --max-time 180 -o "$dest.part" "$url" && [ -s "$dest.part" ]; then
        mv "$dest.part" "$dest"
        echo "  $(du -h "$dest" | cut -f1)"
        return 0
    fi
    rm -f "$dest.part"
    echo "  FAILED to fetch $name from $url"
    return 1
}

echo "real-epubs: fetching into $DEST"
FAILED=0
fetch "https://www.gutenberg.org/ebooks/1342.epub.images" \
    "pride-and-prejudice-epub2-images.epub" "EPUB2, illustrated, English" || FAILED=$((FAILED + 1))
fetch "https://www.gutenberg.org/ebooks/1342.epub3.images" \
    "pride-and-prejudice-epub3-images.epub" "EPUB3, illustrated, same book as above" || FAILED=$((FAILED + 1))
fetch "https://www.gutenberg.org/ebooks/11.epub.noimages" \
    "alice-in-wonderland-epub2-noimages.epub" "EPUB2, no images, English" || FAILED=$((FAILED + 1))
fetch "https://www.gutenberg.org/ebooks/2591.epub.images" \
    "grimms-fairy-tales-epub2-images.epub" "EPUB2, illustrated, many short chapters" || FAILED=$((FAILED + 1))
fetch "https://www.gutenberg.org/ebooks/22367.epub.images" \
    "die-verwandlung-epub2-images.epub" "German, non-ASCII (umlauts)" || FAILED=$((FAILED + 1))
fetch "https://www.gutenberg.org/ebooks/135.epub3.images" \
    "les-miserables-epub3-images.epub" "French, non-ASCII (accents), EPUB3, large" || FAILED=$((FAILED + 1))

echo ""
if [ "$FAILED" -gt 0 ]; then
    echo "real-epubs: $FAILED of 6 could not be fetched – see above. Nothing here was deleted;" \
        "run again once the network is reachable, or proceed with fewer than six."
    exit 1
fi
echo "real-epubs: all 6 present in $DEST"
